### PR TITLE
Harisdev netizen patch 2

### PR DESCRIPTION
**Pull request by harisdev-netizen**
#### ℹ️ Repository information

**The repository has**:

- [x] At least three issues with the `good first issue` label.
- [x] At least 10 contributors.
- [x] Detailed setup instructions for the project.
- [x] CONTRIBUTING.md
- [x] Actively maintained.

### CODE REVIEW

**Comment by harisdev-netizen** [comment]
> #### ℹ️ Repository information
> **The repository has**:
> 
> * [x]  At least three issues with the `good first issue` label.
> * [x]  At least 10 contributors.
> * [x]  Detailed setup instructions for the project.
> * [x]  CONTRIBUTING.md
> * [x]  Actively maintained.

**Review by harisdev-netizen — COMMENTED** [review]
Reviewed

**Review by harisdev-netizen — COMMENTED** [review]
:)

**Review by withshubh — CHANGES_REQUESTED** [review]
Please add it in lexicographic order.

**Comment by withshubh** [comment]
Closing this PR as the repo doesn't meet the required criteria.

**Pull request closed without merging**
