### PR TITLE
Update repositories.toml

### PR DESCRIPTION
**Pull request by shub-garg**
Added https://github.com/shub-garg/Web-Crawler-to-Extract-Longitude---Latitude-from-Google-maps-API

### CODE REVIEW

**Comment by shub-garg** [comment]
Please review

**Review by sanket-deepsource — CHANGES_REQUESTED** [review]
Hi @shub-garg! Thanks for adding your repository to GFI. I can see, however, that your repository doesn't have any issues. Please consider adding a few issues and tagging them as "good first issue", and then we can merge it.

**Comment by shub-garg** [comment]
What issues do you want me to add? sorry I didn't understand @sanket-deepsource

**Comment by sanket-deepsource** [comment]
> What issues do you want me to add? sorry I didn't understand @sanket-deepsource

Good First Issue is an initiative to curate projects that need new contributors. To do that, we expect repositories to have issues created and tagged as "good first issue" that a new contributor can pick up and start contributing to the project. Since your project doesn't have any issues, it will be difficult for new developers to contribute.

I'd recommend that you create issues in your project and tag them as "good first issue" if you are looking to attract contributors.

**Comment by shub-garg** [comment]
So you want me to make some errors in my code, so others can contribute to it? And put it as an issue in the issues section? @sanket-deepsource

**Comment by shub-garg** [comment]
I will do that, today. Give me some time. thank you!

**Comment by shub-garg** [comment]
I have added two issues in my repository as you asked for @sanket-deepsource . Thank you!

**Comment by jai-deepsource** [comment]
Hey there -- thank you for the contribution. Please verify if the repository meets the [criteria](https://github.com/deepsourcelabs/good-first-issue#adding-a-new-project) to list a new project in Good First Issue.

**Pull request closed without merging**
