### PR TITLE
Added new repository from devSouvik

### PR DESCRIPTION
**Pull request by devSouvik**
New repository named personality-tracker added

### CODE REVIEW

**Comment by jai-deepsource** [comment]
@devSouvik Can you add a few more issues that are easy picking? Also, make sure the setup docs are written.

**Comment by devSouvik** [comment]
Within this same repositary ?

**Comment by devSouvik** [comment]
@jai-deepsource I made a few changes, as recommended. Is there anything else to be done?

**Comment by sanket-deepsource** [comment]
Closed due to inactivity. Please open a new PR. Thanks!

**Pull request closed without merging**
