### PR TITLE
Added Strongbox

### PR DESCRIPTION
**Pull request by carlspring**

### CODE REVIEW

**Comment by carlspring** [comment]
Hi,

What else needs to be done in order to get this merged?

Kind regards,

Martin

**Review by jai-deepsource — APPROVED** [review]

**Comment by jai-deepsource** [comment]
@carlspring Merged. Sorry about the delay.

**Comment by carlspring** [comment]
Thanks!

**Comment by carlspring** [comment]
@jai-deepsource ,

Could you please add the `hacktoberfest` topic to your repository and add the label `hacktoberfest-accepted` to this pull request?

**Pull request merged**
