### PR TITLE
Update repositories.toml

### PR DESCRIPTION
**Pull request by William-McGonagle**
#### ℹ️ Repository information

**The repository has**:

- [X] At least three issues with the good first issue label.
- [X] Detailed setup instructions for the project.
- [X] CONTRIBUTING.md
- [X] Actively maintained.

### CODE REVIEW

**Comment by William-McGonagle** [comment]
Am I allowed to add my own project onto here? :)

**Comment by sanket-deepsource** [comment]
> @sanket-deepsource Am I allowed to add my own project onto here? :)

Absolutely, as long as it meets the requirements specified in the PR template. I see that you've missed the comma after your entry, making the TOML invalid. Can you please fix that?

**Comment by William-McGonagle** [comment]
Okie Dokie- Added the comma!

**Review by siddhant-deepsource — APPROVED** [review]
Thanks @William-McGonagle 🙌

**Pull request merged**
