### PR TITLE
Adds Heptagram-Bot/Heptagram

### PR DESCRIPTION
**Pull request by j-dogcoder**

### CODE REVIEW

**Review by sanket-deepsource — CHANGES_REQUESTED** [review]
Can you please add the repository in the correct lexicographic order, and in the correct format?

**Comment by shubhendra-deepsource** [comment]
Hey @j-dogcoder 👋 

Please update the PR with suggested changes!

**Comment by j-dogcoder** [comment]
@shubhendra-deepsource Working on this now!

**Comment by j-dogcoder** [comment]
@shubhendra-deepsource What do you mean by correct format?

**Comment by j-dogcoder** [comment]
I need to open a new issue seeing as my old branch is gone.

**Pull request closed without merging**
