### PR TITLE
feat: add newsletter subscription box to sidebar

### PR DESCRIPTION
**Pull request by rohan-deepsource**
Screenshot 2022-03-14 at 7 10 53 PM

### CODE REVIEW

**Comment by jai-deepsource** [comment]
@sanket-deepsource can you review this?

**Review by sanket-deepsource — CHANGES_REQUESTED** [review]
@rohan-deepsource a few changes:

* Let's just ask for the email address? I think the name isn't required. You can also make the input box full-width.
* The submit button shouldn't be Juniper. It's a secondary action. Can you use the default button?

**Comment by rohan-deepsource** [comment]
@shuvam-deepsource need a VQA here please

**Review by sanket-deepsource — CHANGES_REQUESTED** [review]
CleanShot 2022-03-14 at 18 45 54@2x

**Review by sanket-deepsource — APPROVED** [review]

**Pull request merged**
