### PR TITLE
Add OMRChecker

### PR DESCRIPTION
**Pull request by Udayraj123**
The project is up for hacktoberfest with 3 out of 12 issues marked as good first issue. The repository currently has about 5 contributors over github, although the active developer community on project's discord server is more than 10 people.

#### ℹ️ Repository information

Repo: https://github.com/Udayraj123/OMRChecker/

**The repository has**:

- [X] At least three issues with the `good first issue` label.
- [x] At least 10 contributors.
- [X] Detailed setup instructions for the project.
- [X] CONTRIBUTING.md
- [X] Actively maintained.

### CODE REVIEW

**Comment by Udayraj123** [comment]
@shubhendra-deepsource can you please check this?

**Review by withshubh — APPROVED** [review]

**Comment by Udayraj123** [comment]
@withshubh may I know what happens in this Cloudflare Pages check? Will it succeed on itself?

image

**Comment by Udayraj123** [comment]
@withshubh @shubhendra-deepsource can you please check this?

**Comment by Udayraj123** [comment]
@withshubh It's mid of october. I understand you all are working hard to fix this blocker. But I request manually merging this one-liner if possible as hacktoberfest is passing on

**Comment by Udayraj123** [comment]
It's the last week. @withshubh @shubhendra-deepsource anyone help with merging this?

**Comment by Udayraj123** [comment]
Thank you!

**Pull request merged**
