### PR TITLE
Add external secrets operator

### PR DESCRIPTION
**Pull request by OrlinVasilev**
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>

#### ℹ️ Repository information

**The repository has**:

- [X] At least three issues with the `good first issue` label.
- [X] At least 10 contributors.
- [X] Detailed setup instructions for the project.
- [X] CONTRIBUTING.md
- [X] Actively maintained.

### CODE REVIEW

**Comment by OrlinVasilev** [comment]
@gusfcarvalho @knelasevero FYI :)

**Comment by lucavallin** [comment]
Hey @OrlinVasilev  ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

**Comment by OrlinVasilev** [comment]
Hi @lucavallin that's great but it's hosted not on the initial domain lets try to get someone from the maintainers to confirm their idea with the portal if they will continue working on it

**Comment by OrlinVasilev** [comment]
@tushar-deepsource  @jai-deepsource @siddhant-deepsource  what are the plans for the portal ?

**Comment by tusharsadhwani** [comment]
@OrlinVasilev I recognize that activity on this project has been low, we have plans to start actively maintaining good first issue again.

Please wait a bit more until we can provide a more concrete answer, and thanks for showing interest in the project.

**Comment by OrlinVasilev** [comment]
Hi @tusharsadhwani if you need help with the project obviously I and @lucavallin can jump in and contribute! Just drop a line

**Review by withshubh — APPROVED** [review]
Thanks for listing External Secrets @OrlinVasilev 🙌

**Pull request merged**
