### PR TITLE
Adding kodadot/nft-gallery to good-first issue

### PR DESCRIPTION
**Pull request by yangwao**
- [x] At least three issues with the good first issue label. - [17 at time of making this PR](https://github.com/kodadot/nft-gallery/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

- [x] [Detailed setup instructions for the project.](https://github.com/kodadot/nft-gallery#-play)

- [x] [CONTRIBUTING.md](https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md)

- [x] Actively maintained. - live and funded - https://nft.kodadot.xyz

https://github.com/kodadot/nft-gallery/issues

### CODE REVIEW

**Review by sanket-deepsource — CHANGES_REQUESTED** [review]
Can you please add the repository in the correct lexicographic order?

**Review by shubhendra-deepsource — APPROVED** [review]
Please add the repo in lexicographic order @yangwao

**Comment by yangwao** [comment]
@sanket-deepsource @shubhendra-deepsource just did. I thought I originally posted it right, maybe I had a cursor elsewhere but I was looking to make it in lexicographic order originally. :)

**Comment by shubhendra-deepsource** [comment]
> @sanket-deepsource @shubhendra-deepsource just did. I thought I originally posted it right, maybe I had a cursor elsewhere but I was looking to make it in lexicographic order originally. :)

No worries! @yangwao ✨

**Review by shubhendra-deepsource — APPROVED** [review]

**Comment by yangwao** [comment]
Awesome, thanks for accepting @shubhendra-deepsource !

I've just realized we forked our own repo back in January and hasn't changed the description.
Would that be changed in the next rebuild?

image

now 
image

**Pull request merged**
