### PR TITLE
Show number of comments attached to the issue

### PR DESCRIPTION
**Pull request by pierreyoda**
# #173 Show number of comments attached to the issue

This required updating both the `populate` generator to include the required `comments_count` information, and of course the `RepoBox`'s collapsed issues information.

See the following screenshots for the (responsive) design, including a very simple tooltip:

image

image

### CODE REVIEW

**Review by sanket-deepsource — CHANGES_REQUESTED** [review]
Adding the number of comments is a great idea! Thanks for working on this.

Although I'm not sure if this is the right placement for the count. Can you try placing the count at the end of the comment title? We can also use an icon from vue-feather-icons next to that. Please refer to the mockup:

Group 9

**Comment by pierreyoda** [comment]
Thanks for your rapid answer!

Here is a new, updated version:
image

It still looks a bit weird with long issue titles but otherwise indeed much better.

**Comment by sanket-deepsource** [comment]
Thanks! I've made a few changes to fix the alignment, and I think it'll look better. Can you apply [this patch](https://github.com/deepsourcelabs/good-first-issue/commit/9bccf43f96a090e4b0accd4c3df67e50925a9bab.patch) to your PR?

Screenshot 2021-01-27 at 7 30 54 PM

**Comment by pierreyoda** [comment]
Done and done! There are still two "antipatterns" detected but I feel like those are exaggerated. I will leave you to decide on these.

**Review by sanket-deepsource — APPROVED** [review]

**Comment by sanket-deepsource** [comment]
Merged. Thanks for your work on this! 🙌🏼

**Pull request merged**
