### PR TITLE
Update repositories.toml

### PR DESCRIPTION
**Pull request by kaushikc44**
#### ℹ️ Repository information

https://github.com/kaushikc44/codevim/issues

**The repository has**:

- [x] At least three issues with the `good first issue` label.https://github.com/kaushikc44/codevim/issues
- [ ] At least 10 contributors. None cause I made it individual 
- [x] Detailed setup instructions for the project.https://github.com/kaushikc44/codevim/blob/master/README.md
- [x] CONTRIBUTING.md https://github.com/kaushikc44/codevim/blob/master/DEVELOPER.md
- [x] Actively maintained. yes I keep committing to it.

### CODE REVIEW

**Comment by lucavallin** [comment]
Hey @kaushikc44  ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

**Comment by kaushikc44** [comment]
Feel free to contribute, will commit it have lately been busy with work.

**Comment by lucavallin** [comment]
@kaushikc44 Thanks, great to hear! I don't really use discord but if you open an issue/discussion on my repo I'll be happy to have a chat there!

**Comment by withshubh** [comment]
Hey @kaushikc44 - Thanks for creating the PR. 
To ensure quality and standard, we require at least 10 contributors to add your repository to Good First Issue.
You can check the criteria [here](https://github.com/deepsourcelabs/good-first-issue#adding-a-new-project).

**Comment by kaushikc44** [comment]
Oh I see, sorry about that.

**Pull request closed without merging**
