### PR TITLE
Add label variations for good first issue

### LINKED ISSUE #394: Add label variations for good first issue
I found some project that match the criteria to be added but have variations of the `good first issue` labels like `good-first-issue` and `:wave: Good First Issue` I would like to add these label variations and subsequently add these repos.

Example:
- https://github.com/JetBrains/Exposed/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue
- https://github.com/apollographql/apollo-kotlin/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3Awave%3A+Good+First+Issue%22

I assume that adding these labels to [labels.json](https://github.com/deepsourcelabs/good-first-issue/blob/master/data/labels.json) would be sufficient.

### PR DESCRIPTION
**Pull request by vasanthdharmaraj**
Closes #394

### CODE REVIEW

**Comment by siddhant-deepsource** [comment]
Hey @vasanthdharmaraj, I guess we can surely add the `good-first-issue` label since its close to the default label which we track i.e. `good first issue` and is used by a good number of repos. Regarding adding the `:wave Good First Issue` I guess that is currently being used only in selected repos and not a lot of repos. Thus, it would be an overkill to add that as of now since according to the current implementation we check for the presence of these labels across all the repositories listed in `data/repositories.toml`.

Thus, would be great if you can only add the `good-first-issue` label. Thanks for contributing 🙌

**Comment by siddhant-deepsource** [comment]
Hey @vasanthdharmaraj, I guess we can surely add the `good-first-issue` label since its close to the default label which we track i.e. `good first issue` and is used by a good number of repos. Regarding adding the `:wave Good First Issue` I guess that is currently being used only in selected repos and not a lot of repos. Thus, it would be an overkill to add that as of now since according to the current implementation we check for the presence of these labels across all the repositories listed in `data/repositories.toml`.

Thus, would be great if you can only add the `good-first-issue` label. Thanks for contributing 🙌

**Comment by vasanthdharmaraj** [comment]
> Hey @vasanthdharmaraj, I guess we can surely add the `good-first-issue` label since its close to the default label which we track i.e. `good first issue` and is used by a good number of repos. Regarding adding the `:wave: Good First Issue` label, I guess that is currently being used only in selected repos and not a lot of repos. Thus, it would be an overkill to add that as of now since according to the current implementation we check for the presence of these labels across all the repositories listed in `data/repositories.toml`.
> 
> Thus, would be great if you can only add the `good-first-issue` label. Thanks for contributing 🙌

Makes sense. Removed `:wave: Good First Issue` as it is not a common label.

**Review by siddhant-deepsource — APPROVED** [review]

**Comment by siddhant-deepsource** [comment]
Hey @vasanthdharmaraj Can you please sync the branch of your fork with the upstream i.e. this repo? That would fix the netlify builds hopefully. Thanks 🙌

**Comment by jai-deepsource** [comment]
Opened a PR - https://github.com/deepsourcelabs/good-first-issue/pull/418

**Pull request closed without merging**
