### PR TITLE
add: open-source projects

### PR DESCRIPTION
**Pull request by kabir0x23**
#### ℹ️ Repository information

**The repository has**:

- [x] At least three issues with the `good first issue` label.
- [x] At least 10 contributors.
- [x] Detailed setup instructions for the project.
- [x] CONTRIBUTING.md
- [x] Actively maintained.

12 issues got assigned, working on new issues.

### CODE REVIEW

**Review by withshubh — CHANGES_REQUESTED** [review]
Only 1 repository meets the criteria to be listed which is `github.com/thecyberworld/thecyberhub.org`. Please remove the other one.

**Comment by kabir0x23** [comment]
> Only 1 repository meets the criteria to be listed which is `github.com/thecyberworld/thecyberhub.org`. Please remove the other one.

done 😄

**Review by withshubh — APPROVED** [review]

**Review by siddhant-deepsource — APPROVED** [review]

**Comment by kabir0x23** [comment]
Just have a question:

How much time will take to get my PR merged?

**Comment by lucavallin** [comment]
Hey @kabir0x23  ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

**Pull request closed without merging**
